<?php

/**
 * @file
 * Contains student_payment.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function student_payment_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the student_payment module.
    case 'help.page.student_payment':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
// function student_payment_theme() {
//   return [
//     'student_payment' => [
//       'render element' => 'children',
//     ],
//   ];
//}

/**
 * Implements hook_theme().
 */
function student_payment_theme() {
  $theme = [];
  $theme['stud_pay_mgnt3'] = [
    'render element' => 'elements',
    'file' => 'stud_pay_mgnt3.page.inc',
    'template' => 'stud_pay_mgnt3',
  ];
  $theme['stud_pay_mgnt3_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'stud_pay_mgnt3.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function student_payment_theme_suggestions_stud_pay_mgnt3(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#stud_pay_mgnt3'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'stud_pay_mgnt3__' . $sanitized_view_mode;
  $suggestions[] = 'stud_pay_mgnt3__' . $entity->bundle();
  $suggestions[] = 'stud_pay_mgnt3__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'stud_pay_mgnt3__' . $entity->id();
  $suggestions[] = 'stud_pay_mgnt3__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
