student_payment.stud_pay_mgnt3_type.*:
  type: config_entity
  label: 'Stud pay mgnt3 type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
